set(_CATKIN_CURRENT_PACKAGE "intersection_control")
set(intersection_control_VERSION "1.0.0")
set(intersection_control_MAINTAINER "Mack <mack@duckietown.org>")
set(intersection_control_PACKAGE_FORMAT "1")
set(intersection_control_BUILD_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(intersection_control_BUILD_EXPORT_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(intersection_control_BUILDTOOL_DEPENDS "catkin")
set(intersection_control_BUILDTOOL_EXPORT_DEPENDS )
set(intersection_control_EXEC_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(intersection_control_RUN_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(intersection_control_TEST_DEPENDS )
set(intersection_control_DOC_DEPENDS )
set(intersection_control_DEPRECATED "")