#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/yunfantang/duckietown/catkin_ws/devel_isolated/ground_projection:/home/yunfantang/duckietown/catkin_ws/devel_isolated/fsm:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_regression:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_node:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_logs:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_algo:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_unit_test:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckiebot_visualizer:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckie_rr_bridge:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_filtering_swaggyduck:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_augmented_reality_swaggyduck:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt-live-instagram_swaggyduck:/home/yunfantang/duckietown/catkin_ws/devel_isolated/complete_image_pipeline:/home/yunfantang/duckietown/catkin_ws/devel_isolated/anti_instagram:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_msgs:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_logs:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_description:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_demos:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckieteam:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltags:/home/yunfantang/duckietown/catkin_ws/devel_isolated/adafruit_drivers:/home/yunfantang/duckietown/catkin_ws/devel:/opt/ros/kinetic:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltagscpp"
export LD_LIBRARY_PATH="/home/yunfantang/duckietown/catkin_ws/devel_isolated/fsm/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_regression/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_node/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_logs/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_algo/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_unit_test/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckiebot_visualizer/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckie_rr_bridge/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_filtering_swaggyduck/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_augmented_reality_swaggyduck/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt-live-instagram_swaggyduck/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/complete_image_pipeline/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/anti_instagram/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_msgs/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_logs/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_description/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_demos/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckieteam/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltags/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/adafruit_drivers/lib:/home/yunfantang/duckietown/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltagscpp/lib"
export ROSLISP_PACKAGE_DIRECTORIES="/home/yunfantang/duckietown/catkin_ws/devel_isolated/ground_projection/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/yunfantang/duckietown/catkin_ws/src/10-lane-control/ground_projection:$ROS_PACKAGE_PATH"