set(_CATKIN_CURRENT_PACKAGE "traffic_light")
set(traffic_light_VERSION "1.0.0")
set(traffic_light_MAINTAINER "Mack <mack@duckietown.org>")
set(traffic_light_PACKAGE_FORMAT "1")
set(traffic_light_BUILD_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(traffic_light_BUILD_EXPORT_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(traffic_light_BUILDTOOL_DEPENDS "catkin")
set(traffic_light_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_EXEC_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(traffic_light_RUN_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(traffic_light_TEST_DEPENDS )
set(traffic_light_DOC_DEPENDS )
set(traffic_light_DEPRECATED "")