set(_CATKIN_CURRENT_PACKAGE "duckietown_logs")
set(duckietown_logs_VERSION "1.0.0")
set(duckietown_logs_MAINTAINER "Andrea Censi <acensi@idsc.mavt.ethz.ch>")
set(duckietown_logs_PACKAGE_FORMAT "1")
set(duckietown_logs_BUILD_DEPENDS )
set(duckietown_logs_BUILD_EXPORT_DEPENDS )
set(duckietown_logs_BUILDTOOL_DEPENDS "catkin")
set(duckietown_logs_BUILDTOOL_EXPORT_DEPENDS )
set(duckietown_logs_EXEC_DEPENDS )
set(duckietown_logs_RUN_DEPENDS )
set(duckietown_logs_TEST_DEPENDS )
set(duckietown_logs_DOC_DEPENDS )
set(duckietown_logs_DEPRECATED "")