import os

from duckietown_utils import logger
from duckietown_utils.constants import get_list_of_packages_in_catkin_ws

from .configuration import EasyNodeConfig
from .configuration import PROCESS_THREADED
from .configuration import load_configuration_for_nodes_in_package
from duckietown_utils.read_package_xml import read_package_xml_info, Person,\
    PackageXML


def generate_easy_node_docs():
    skip = ['easier_node']
    packages = get_list_of_packages_in_catkin_ws()
    logger.info('Looking in %d packages for nodes.' % len(packages))

    for package_name, package_dir in packages.items():
        md = ""

        package_xml = os.path.join(package_dir, 'package.xml')
        package_info = read_package_xml_info(package_xml)
        md += generate_from_package_info(package_info, package_dir)

        configs = load_configuration_for_nodes_in_package(package_name)
        for node_name, config in configs.items():
            if node_name in skip:
                continue
            md += generate_from_node_config(config)

        out = os.path.join(package_dir,  '.autogenerated.md')
        write_to_file_if_changed(out, md)

branch = 'andrea-config'
S = '\n\n'
    
def generate_from_package_info(info, package_dir):
    assert isinstance(info, PackageXML)
    md = ''
    md += "<div id='%s-autogenerated' markdown='1'>\n\n" % (info.name)
    md += '\n<!-- do not edit this file, autogenerated -->\n\n'

    
    parent = os.path.basename(os.path.dirname(package_dir))
    unique = '%s/%s' % (parent, info.name)
#     if info.name not in  ['led_emitter']:
    # XXX current branch
    
    md += '[Link to package on Github](github:org=duckietown,repo=Software,path=%s,branch=%s)' % (unique, branch) + S

    for p in info.authors:
        md += 'Author: ' + format_person(p) + S

    if not info.authors:
        md += 'No authors specified.' + S

    for p in info.maintainers:
        md += 'Maintainer: ' + format_person(p) + S

    if not info.maintainers:
        md += 'No maintainers specified.' + S

    if info.description:
        md += info.description + S
    else:
        md += 'TODO: no package description found.'

    md += S + '</div>' + S

    return md


def format_person(p):
    assert isinstance(p, Person)
    if p.email:
        return '[%s](mailto:%s)' % (p.name, p.email)
    else:
        return p.name


def generate_from_node_config(config):
    md = ''
    md += '<!-- file start -->\n\n'
    md += "<div id='%s-%s-autogenerated' markdown='1'>\n\n" % (
        config.package_name, config.node_type_name)
    md += '\n<!-- do not edit this file, autogenerated -->\n\n'
    
    assert isinstance(config, EasyNodeConfig)
    short = os.path.basename(config.filename)
    md += '(Generated from [configuration `%s`]' % short
    md += '(github:org=duckietown,repo=Software,path=%s,branch=%s).)' % (short, branch) + S

    if config.description is None:
        md += 'TODO: Missing node description in `%s`.\n\n' % os.path.basename(
            config.filename)
    else:
        md += config.description + '\n\n'
    md += generate_configuration(config)
    md += '\n\n</div>'
    return md


def write_to_file_if_changed(filename, contents):
    if os.path.exists(filename):
        existing = open(filename).read()
        need_write = existing != contents
    else:
        need_write = True

    if need_write:
        with open(filename, 'w') as f:
            f.write(contents)
        logger.info('Written to %s' % filename)
    else:
        logger.info('File already up to date %s' % filename)


def write_desc(x):
    return 'TODO: Missing description for entry "`%s`".' % x.name

# @contract(config=EasyNodeConfig)


def generate_configuration(config):
    assert isinstance(config, EasyNodeConfig)
    md = ""
    COMMON_PREFIX = 'en_'

    choose = [_ for _ in config.parameters.values(
    ) if not _.name.startswith(COMMON_PREFIX)]

    md += '### Parameters \n\n'

    if not choose:
        md += 'No parameters defined.\n\n'

    for param in choose:
        md += "**Parameter `%s`**: " % param.name
        md += describe_type(param.type)
        if param.has_default:
            md += '; default value: `%r`' % param.default
        md += '\n\n'
        if param.desc:
            md += param.desc
        else:
            md += write_desc(param)

        md += '\n\n'

    md += '### Subscriptions \n\n'

    if not config.subscriptions:
        md += 'No subscriptions defined.\n\n'

    for subscription in config.subscriptions.values():
        md += "**Subscription `%s`**: " % subscription.name
        md += 'topic `%s` (%s)\n\n' % (subscription.topic,
                                       describe_type(subscription.type))

        if subscription.desc:
            md += subscription.desc
        else:
            md += write_desc(subscription)

        md += '\n\n'

        if subscription.process == PROCESS_THREADED:
            md += 'Note: The data is processed *asynchronously* in a different thread.\n\n'

    md += '### Publishers \n\n'

    if not config.publishers:
        md += 'No publishers defined.\n\n'

    for publisher in config.publishers.values():
        md += "**Publisher `%s`**: " % publisher.name
        md += 'topic `%s` (%s)\n\n' % (publisher.topic,
                                       describe_type(publisher.type))
        if publisher.desc:
            md += publisher.desc
        else:
            md += write_desc(publisher)

        md += '\n\n'


#     md += '### Services \n\n'
#
#
#     md += '(EasyNode does not parse services.\n\n')

    return md


def describe_type(x):
    if x is None:
        return 'not known'
    else:
        return '`%s`' % x.__name__
