set(_CATKIN_CURRENT_PACKAGE "parallel_autonomy")
set(parallel_autonomy_VERSION "1.0.0")
set(parallel_autonomy_MAINTAINER "Liam Paull <lpaull@mit.edu>")
set(parallel_autonomy_PACKAGE_FORMAT "1")
set(parallel_autonomy_BUILD_DEPENDS "duckietown_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(parallel_autonomy_BUILD_EXPORT_DEPENDS "duckietown_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(parallel_autonomy_BUILDTOOL_DEPENDS "catkin")
set(parallel_autonomy_BUILDTOOL_EXPORT_DEPENDS )
set(parallel_autonomy_EXEC_DEPENDS "duckietown_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(parallel_autonomy_RUN_DEPENDS "duckietown_msgs" "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(parallel_autonomy_TEST_DEPENDS )
set(parallel_autonomy_DOC_DEPENDS )
set(parallel_autonomy_DEPRECATED "")