set(parallel_autonomy_SETUP_PY_VERSION "1.0.0")
set(parallel_autonomy_SETUP_PY_SCRIPTS "")
set(parallel_autonomy_SETUP_PY_PACKAGES "parallel_autonomy")
set(parallel_autonomy_SETUP_PY_PACKAGE_DIRS "include/parallel_autonomy")
set(parallel_autonomy_SETUP_PY_MODULES "")
set(parallel_autonomy_SETUP_PY_MODULE_DIRS "")