set(_CATKIN_CURRENT_PACKAGE "duckieteam")
set(duckieteam_VERSION "1.0.0")
set(duckieteam_MAINTAINER "Andrea Censi <acensi@idsc.mavt.ethz.ch>")
set(duckieteam_PACKAGE_FORMAT "1")
set(duckieteam_BUILD_DEPENDS "rospy")
set(duckieteam_BUILD_EXPORT_DEPENDS "rospy")
set(duckieteam_BUILDTOOL_DEPENDS "catkin")
set(duckieteam_BUILDTOOL_EXPORT_DEPENDS )
set(duckieteam_EXEC_DEPENDS "rospy")
set(duckieteam_RUN_DEPENDS "rospy")
set(duckieteam_TEST_DEPENDS )
set(duckieteam_DOC_DEPENDS )
set(duckieteam_DEPRECATED "")