#!/bin/bash

# Argument check: show usage
if [[ $# -ne 2 ]] ; then
    echo "Usage:"
    echo "Important: the script MUST be run from its location!"
    echo "./install_fleet_messaging <wifi-iface> <static-ip>"
    echo "Write arguments without <>."
    echo "<wifi-iface> is a WiFi interface that can be found with iwconfig."
    echo "(interface used for the mesh network)"
    echo "<static-ip> is a static IP address for the duckiebot."
    echo "Every duckiebot needs a UNIQUE IP address!"
    exit 1
fi
WIFACE=$1
IPADDR=$2

# Check the interface
for item in "$@" ; do
    # Remove argument for $DUCKIETOWN_ROOT/environment.sh
    shift;
done
iwconfig $WIFACE | grep -v "no wireless extensions."
if [[ $? -ne 0 ]] ; then
    echo "Aborting...Interface" $WIFACE "is not a WiFi interface!"
    exit 2
fi

source $DUCKIETOWN_ROOT/environment.sh
if [[ $? -ne 0 ]] ; then
    echo "Aborting...there is something wrong with the environment!"
    exit 3
fi

# Install ZeroMQ
./install_zmq
if [[ $? -ne 0 ]] ; then
    echo "Aborting...installing ZeroMQ failed!"
    exit 4
fi

# Install ProtoBuf
./install_protobuf

# Install the mesh network
./install_meshnet $WIFACE $IPADDR
