#!/usr/bin/env python
# @create-shortcut-for-this

from rgb_led import *
import sys

# if len(sys.argv) <= 1:
# 	pattern = 'blinking1'
# else:
# 	pattern = sys.argv[1]

try:
	conf_all_on(GREEN)
except ValueError as e:
	print(e)
	sys.exit(1)
