#!/usr/bin/env python
from rgb_led import *
import time
from rgb_led.duckietown_lights import DuckietownLights
from rgb_led import RGB_LED, LED


def cycle_LEDs_fancy1(speed=5):
    led = RGB_LED()

    from math import sin, cos

    t0 = time.time()

    def get_config(t):
        t = t * speed
        a = 0.5 + 0.5 * cos(t)
        b = 0.5 + 0.5 * sin(t)
        c = 0.5 + 0.5 * cos(2 * t)

        return {
            LED.TOP: [a, b, c],
            LED.BACK_LEFT: [b, c, a],
            LED.BACK_RIGHT: [a, c, b],
            LED.FRONT_LEFT: [b, a, c],
            LED.FRONT_RIGHT: [c, a, b],
        }

    while True:
        t = time.time()
        config = get_config(t)
        for name, col in config.items():
            k = DuckietownLights.name2port[name]
            led.setRGB(k, col)
        time.sleep(0.01)


if __name__ == "__main__":
    cycle_LEDs_fancy1()
