#!/usr/bin/env python

import time
from time import sleep
from rgb_led import RGB_LED, Fancy2


def cycle_leds(speed=5):
    led = RGB_LED()

    pattern = Fancy2()

    while True:
        t = time.time()
        config = pattern.get_configuration(t)
        for name, col in config.items():

            k = RGB_LED.PORT_MAPPING[name]
            led.setRGB(k, col)
        sleep(0.01)


if __name__ == '__main__':
    cycle_leds()
