set(_CATKIN_CURRENT_PACKAGE "mdoap")
set(mdoap_VERSION "1.0.0")
set(mdoap_MAINTAINER "Mack <mack@duckietown.org>")
set(mdoap_PACKAGE_FORMAT "1")
set(mdoap_BUILD_DEPENDS "duckietown_msgs" "roscpp" "rospy")
set(mdoap_BUILD_EXPORT_DEPENDS "duckietown_msgs" "roscpp" "rospy")
set(mdoap_BUILDTOOL_DEPENDS "catkin")
set(mdoap_BUILDTOOL_EXPORT_DEPENDS )
set(mdoap_EXEC_DEPENDS "duckietown_msgs" "roscpp" "rospy")
set(mdoap_RUN_DEPENDS "duckietown_msgs" "roscpp" "rospy")
set(mdoap_TEST_DEPENDS )
set(mdoap_DOC_DEPENDS )
set(mdoap_DEPRECATED "")