set(mdoap_SETUP_PY_VERSION "1.0.0")
set(mdoap_SETUP_PY_SCRIPTS "")
set(mdoap_SETUP_PY_PACKAGES "mdoap")
set(mdoap_SETUP_PY_PACKAGE_DIRS "include/mdoap")
set(mdoap_SETUP_PY_MODULES "")
set(mdoap_SETUP_PY_MODULE_DIRS "")