set(_CATKIN_CURRENT_PACKAGE "led_emitter")
set(led_emitter_VERSION "1.0.0")
set(led_emitter_MAINTAINER "Andrea Censi <acensi@idsc.mavt.ethz.ch>")
set(led_emitter_PACKAGE_FORMAT "1")
set(led_emitter_BUILD_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(led_emitter_BUILD_EXPORT_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(led_emitter_BUILDTOOL_DEPENDS "catkin")
set(led_emitter_BUILDTOOL_EXPORT_DEPENDS )
set(led_emitter_EXEC_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(led_emitter_RUN_DEPENDS "duckietown_msgs" "rgb_led" "roscpp" "rospy")
set(led_emitter_TEST_DEPENDS )
set(led_emitter_DOC_DEPENDS )
set(led_emitter_DEPRECATED "")