set(_CATKIN_CURRENT_PACKAGE "localization")
set(localization_VERSION "1.0.0")
set(localization_MAINTAINER "Mack <mack@duckietown.org>")
set(localization_PACKAGE_FORMAT "1")
set(localization_BUILD_DEPENDS "apriltags" "geometry_msgs" "duckietown_msgs" "roscpp" "rospy" "tf" "tf2_ros")
set(localization_BUILD_EXPORT_DEPENDS "apriltags" "geometry_msgs" "duckietown_msgs" "roscpp" "rospy" "tf" "tf2_ros")
set(localization_BUILDTOOL_DEPENDS "catkin")
set(localization_BUILDTOOL_EXPORT_DEPENDS )
set(localization_EXEC_DEPENDS "apriltags" "geometry_msgs" "duckietown_msgs" "roscpp" "rospy" "tf" "tf2_ros")
set(localization_RUN_DEPENDS "apriltags" "geometry_msgs" "duckietown_msgs" "roscpp" "rospy" "tf" "tf2_ros")
set(localization_TEST_DEPENDS "gtest")
set(localization_DOC_DEPENDS )
set(localization_DEPRECATED "")