set(_CATKIN_CURRENT_PACKAGE "what_the_duck")
set(what_the_duck_VERSION "1.0.0")
set(what_the_duck_MAINTAINER "Andrea Censi <acensi@idsc.mavt.ethz.ch>")
set(what_the_duck_PACKAGE_FORMAT "1")
set(what_the_duck_BUILD_DEPENDS )
set(what_the_duck_BUILD_EXPORT_DEPENDS )
set(what_the_duck_BUILDTOOL_DEPENDS "catkin")
set(what_the_duck_BUILDTOOL_EXPORT_DEPENDS )
set(what_the_duck_EXEC_DEPENDS )
set(what_the_duck_RUN_DEPENDS )
set(what_the_duck_TEST_DEPENDS )
set(what_the_duck_DOC_DEPENDS )
set(what_the_duck_DEPRECATED "")