set(_CATKIN_CURRENT_PACKAGE "rgb_led")
set(rgb_led_VERSION "1.0.0")
set(rgb_led_MAINTAINER "Mack <mack@duckietown.org>")
set(rgb_led_PACKAGE_FORMAT "1")
set(rgb_led_BUILD_DEPENDS "duckietown_msgs" "rospy")
set(rgb_led_BUILD_EXPORT_DEPENDS "duckietown_msgs" "rospy")
set(rgb_led_BUILDTOOL_DEPENDS "catkin")
set(rgb_led_BUILDTOOL_EXPORT_DEPENDS )
set(rgb_led_EXEC_DEPENDS "duckietown_msgs" "rospy")
set(rgb_led_RUN_DEPENDS "duckietown_msgs" "rospy")
set(rgb_led_TEST_DEPENDS )
set(rgb_led_DOC_DEPENDS )
set(rgb_led_DEPRECATED "")