set(_CATKIN_CURRENT_PACKAGE "dt-live-instagram_swaggyduck")
set(dt-live-instagram_swaggyduck_VERSION "1.0.0")
set(dt-live-instagram_swaggyduck_MAINTAINER "Yunfan Tang <yunfantang@uchicago.edu>")
set(dt-live-instagram_swaggyduck_PACKAGE_FORMAT "1")
set(dt-live-instagram_swaggyduck_BUILD_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt-live-instagram_swaggyduck_BUILD_EXPORT_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt-live-instagram_swaggyduck_BUILDTOOL_DEPENDS "catkin")
set(dt-live-instagram_swaggyduck_BUILDTOOL_EXPORT_DEPENDS )
set(dt-live-instagram_swaggyduck_EXEC_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt-live-instagram_swaggyduck_RUN_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt-live-instagram_swaggyduck_TEST_DEPENDS )
set(dt-live-instagram_swaggyduck_DOC_DEPENDS )
set(dt-live-instagram_swaggyduck_DEPRECATED "")