set(_CATKIN_CURRENT_PACKAGE "veh_coordinator")
set(veh_coordinator_VERSION "0.0.1")
set(veh_coordinator_MAINTAINER "Mack <mack@duckietown.org>")
set(veh_coordinator_PACKAGE_FORMAT "1")
set(veh_coordinator_BUILD_DEPENDS "duckietown_msgs" "rospy" "std_msgs")
set(veh_coordinator_BUILD_EXPORT_DEPENDS "duckietown_msgs" "rospy" "std_msgs")
set(veh_coordinator_BUILDTOOL_DEPENDS "catkin")
set(veh_coordinator_BUILDTOOL_EXPORT_DEPENDS )
set(veh_coordinator_EXEC_DEPENDS "duckietown_msgs" "rospy" "std_msgs")
set(veh_coordinator_RUN_DEPENDS "duckietown_msgs" "rospy" "std_msgs")
set(veh_coordinator_TEST_DEPENDS )
set(veh_coordinator_DOC_DEPENDS )
set(veh_coordinator_DEPRECATED "")