#!/usr/bin/env python
from duckietown_utils.exceptions import wrap_script_entry_point
from easy_node.user_config.summary import user_config_summary
from duckietown_utils import col_logging  # @UnusedImport

def print_summary():
    s = user_config_summary()
    print(s)
        
    
if __name__ == '__main__':
    wrap_script_entry_point(print_summary)