set(_CATKIN_CURRENT_PACKAGE "duckietown_unit_test")
set(duckietown_unit_test_VERSION "1.0.0")
set(duckietown_unit_test_MAINTAINER "Mack <mack@duckietown.org>")
set(duckietown_unit_test_PACKAGE_FORMAT "1")
set(duckietown_unit_test_BUILD_DEPENDS )
set(duckietown_unit_test_BUILD_EXPORT_DEPENDS )
set(duckietown_unit_test_BUILDTOOL_DEPENDS "catkin")
set(duckietown_unit_test_BUILDTOOL_EXPORT_DEPENDS )
set(duckietown_unit_test_EXEC_DEPENDS )
set(duckietown_unit_test_RUN_DEPENDS )
set(duckietown_unit_test_TEST_DEPENDS )
set(duckietown_unit_test_DOC_DEPENDS )
set(duckietown_unit_test_DEPRECATED "")