set(_CATKIN_CURRENT_PACKAGE "duckie_rr_bridge")
set(duckie_rr_bridge_VERSION "1.0.0")
set(duckie_rr_bridge_MAINTAINER "Mack <mack@duckietown.org>")
set(duckie_rr_bridge_PACKAGE_FORMAT "1")
set(duckie_rr_bridge_BUILD_DEPENDS "RobotRaconteur" "duckietown_msgs" "rospy" "std_msgs" "sensor_msgs")
set(duckie_rr_bridge_BUILD_EXPORT_DEPENDS "RobotRaconteur" "duckietown_msgs" "rospy" "std_msgs" "sensor_msgs")
set(duckie_rr_bridge_BUILDTOOL_DEPENDS "catkin")
set(duckie_rr_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(duckie_rr_bridge_EXEC_DEPENDS "RobotRaconteur" "duckietown_msgs" "rospy" "std_msgs" "sensor_msgs")
set(duckie_rr_bridge_RUN_DEPENDS "RobotRaconteur" "duckietown_msgs" "rospy" "std_msgs" "sensor_msgs")
set(duckie_rr_bridge_TEST_DEPENDS )
set(duckie_rr_bridge_DOC_DEPENDS )
set(duckie_rr_bridge_DEPRECATED "")