set(_CATKIN_CURRENT_PACKAGE "pkg_name")
set(pkg_name_VERSION "1.0.0")
set(pkg_name_MAINTAINER "Andrea Censi <acensi@idsc.mavt.ethz.ch>")
set(pkg_name_PACKAGE_FORMAT "1")
set(pkg_name_BUILD_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(pkg_name_BUILD_EXPORT_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(pkg_name_BUILDTOOL_DEPENDS "catkin")
set(pkg_name_BUILDTOOL_EXPORT_DEPENDS )
set(pkg_name_EXEC_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(pkg_name_RUN_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(pkg_name_TEST_DEPENDS )
set(pkg_name_DOC_DEPENDS )
set(pkg_name_DEPRECATED "")