#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/yunfantang/duckietown/catkin_ws/devel_isolated/pkg_name:/home/yunfantang/duckietown/catkin_ws/devel_isolated/pi_camera:/home/yunfantang/duckietown/catkin_ws/devel_isolated/parallel_autonomy:/home/yunfantang/duckietown/catkin_ws/devel_isolated/navigation:/home/yunfantang/duckietown/catkin_ws/devel_isolated/mdoap:/home/yunfantang/duckietown/catkin_ws/devel_isolated/localization:/home/yunfantang/duckietown/catkin_ws/devel_isolated/line_detector2:/home/yunfantang/duckietown/catkin_ws/devel_isolated/line_detector:/home/yunfantang/duckietown/catkin_ws/devel_isolated/led_joy_mapper:/home/yunfantang/duckietown/catkin_ws/devel_isolated/led_interpreter:/home/yunfantang/duckietown/catkin_ws/devel_isolated/led_detection:/home/yunfantang/duckietown/catkin_ws/devel_isolated/lane_filter:/home/yunfantang/duckietown/catkin_ws/devel_isolated/lane_control:/home/yunfantang/duckietown/catkin_ws/devel_isolated/joy_mapper:/home/yunfantang/duckietown/catkin_ws/devel_isolated/intersection_control:/home/yunfantang/duckietown/catkin_ws/devel_isolated/indefinite_navigation:/home/yunfantang/duckietown/catkin_ws/devel_isolated/ground_projection:/home/yunfantang/duckietown/catkin_ws/devel_isolated/fsm:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_regression:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_node:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_logs:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_algo:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_unit_test:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckiebot_visualizer:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckie_rr_bridge:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_filtering_swaggyduck:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_augmented_reality_swaggyduck:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt-live-instagram_swaggyduck:/home/yunfantang/duckietown/catkin_ws/devel_isolated/complete_image_pipeline:/home/yunfantang/duckietown/catkin_ws/devel_isolated/anti_instagram:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_msgs:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_logs:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_description:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_demos:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckieteam:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltags:/home/yunfantang/duckietown/catkin_ws/devel_isolated/adafruit_drivers:/home/yunfantang/duckietown/catkin_ws/devel:/opt/ros/kinetic:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltagscpp"
export LD_LIBRARY_PATH="/home/yunfantang/duckietown/catkin_ws/devel_isolated/pi_camera/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/parallel_autonomy/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/navigation/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/mdoap/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/localization/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/line_detector2/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/line_detector/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/led_joy_mapper/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/led_interpreter/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/led_detection/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/lane_filter/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/lane_control/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/joy_mapper/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/intersection_control/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/indefinite_navigation/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/ground_projection/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/fsm/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_regression/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_node/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_logs/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/easy_algo/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_unit_test/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckiebot_visualizer/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckie_rr_bridge/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_filtering_swaggyduck/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt_augmented_reality_swaggyduck/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/dt-live-instagram_swaggyduck/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/complete_image_pipeline/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/anti_instagram/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_msgs/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_logs/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_description/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown_demos/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckietown/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/duckieteam/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltags/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/adafruit_drivers/lib:/home/yunfantang/duckietown/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/home/yunfantang/duckietown/catkin_ws/devel_isolated/apriltagscpp/lib"
export ROSLISP_PACKAGE_DIRECTORIES="/home/yunfantang/duckietown/catkin_ws/devel_isolated/pkg_name/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/yunfantang/duckietown/catkin_ws/src/60-templates/pkg_name:$ROS_PACKAGE_PATH"