set(_CATKIN_CURRENT_PACKAGE "rostest_example")
set(rostest_example_VERSION "1.0.0")
set(rostest_example_MAINTAINER "Mack <mack@duckietown.org>")
set(rostest_example_PACKAGE_FORMAT "1")
set(rostest_example_BUILD_DEPENDS "roscpp" "rospy")
set(rostest_example_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(rostest_example_BUILDTOOL_DEPENDS "catkin")
set(rostest_example_BUILDTOOL_EXPORT_DEPENDS )
set(rostest_example_EXEC_DEPENDS "roscpp" "rospy")
set(rostest_example_RUN_DEPENDS "roscpp" "rospy")
set(rostest_example_TEST_DEPENDS "unittest")
set(rostest_example_DOC_DEPENDS )
set(rostest_example_DEPRECATED "")