set(rostest_example_SETUP_PY_VERSION "1.0.0")
set(rostest_example_SETUP_PY_SCRIPTS "")
set(rostest_example_SETUP_PY_PACKAGES "rostest_example")
set(rostest_example_SETUP_PY_PACKAGE_DIRS "include/rostest_example")
set(rostest_example_SETUP_PY_MODULES "")
set(rostest_example_SETUP_PY_MODULE_DIRS "")