# CMake generated Testfile for 
# Source directory: /home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example
# Build directory: /home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rostest_example_rostest_tests_quacker_tester.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results/rostest_example/rostest-tests_quacker_tester.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example --package=rostest_example --results-filename tests_quacker_tester.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results\" /home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example/tests/quacker_tester.test ")
add_test(_ctest_rostest_example_rostest_tests_average_quacks_tester_node.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results/rostest_example/rostest-tests_average_quacks_tester_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example --package=rostest_example --results-filename tests_average_quacks_tester_node.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results\" /home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example/tests/average_quacks_tester_node.test ")
add_test(_ctest_rostest_example_rostest_tests_duckiecall_tester_node.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results/rostest_example/rostest-tests_duckiecall_tester_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example --package=rostest_example --results-filename tests_duckiecall_tester_node.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results\" /home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example/tests/duckiecall_tester_node.test ")
add_test(_ctest_rostest_example_rostest_tests_rostest_example_tester_node.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results/rostest_example/rostest-tests_rostest_example_tester_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example --package=rostest_example --results-filename tests_rostest_example_tester_node.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/rostest_example/test_results\" /home/yunfantang/duckietown/catkin_ws/src/60-templates/rostest_example/tests/rostest_example_tester_node.test ")
subdirs(gtest)
