# CMake generated Testfile for 
# Source directory: /home/yunfantang/duckietown/catkin_ws/src/30-localization-and-planning/duckietown_description
# Build directory: /home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_duckietown_description_rostest_tests_duckietown_description_tester_node.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description/test_results/duckietown_description/rostest-tests_duckietown_description_tester_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/30-localization-and-planning/duckietown_description --package=duckietown_description --results-filename tests_duckietown_description_tester_node.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description/test_results\" /home/yunfantang/duckietown/catkin_ws/src/30-localization-and-planning/duckietown_description/tests/duckietown_description_tester_node.test ")
add_test(_ctest_duckietown_description_rostest_tests_map_generation_tester.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description/test_results/duckietown_description/rostest-tests_map_generation_tester.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/30-localization-and-planning/duckietown_description --package=duckietown_description --results-filename tests_map_generation_tester.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/duckietown_description/test_results\" /home/yunfantang/duckietown/catkin_ws/src/30-localization-and-planning/duckietown_description/tests/map_generation_tester.test ")
subdirs(gtest)
