# CMake generated Testfile for 
# Source directory: /home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram
# Build directory: /home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_anti_instagram_rostest_tests_antiinstagram_correctness_test.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/test_results/anti_instagram/rostest-tests_antiinstagram_correctness_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram --package=anti_instagram --results-filename tests_antiinstagram_correctness_test.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/test_results\" /home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram/tests/antiinstagram_correctness_test.test ")
add_test(_ctest_anti_instagram_rostest_tests_antiinstagram_stub_test.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/test_results/anti_instagram/rostest-tests_antiinstagram_stub_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram --package=anti_instagram --results-filename tests_antiinstagram_stub_test.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/test_results\" /home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram/tests/antiinstagram_stub_test.test ")
add_test(_ctest_anti_instagram_rostest_tests_antiinstagram_performance_test.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/test_results/anti_instagram/rostest-tests_antiinstagram_performance_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram --package=anti_instagram --results-filename tests_antiinstagram_performance_test.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/anti_instagram/test_results\" /home/yunfantang/duckietown/catkin_ws/src/10-lane-control/anti_instagram/tests/antiinstagram_performance_test.test ")
subdirs(gtest)
