set(_CATKIN_CURRENT_PACKAGE "dt_augmented_reality_swaggyduck")
set(dt_augmented_reality_swaggyduck_VERSION "1.0.0")
set(dt_augmented_reality_swaggyduck_MAINTAINER "Yunfan Tang <yunfantang@uchicago.edu>")
set(dt_augmented_reality_swaggyduck_PACKAGE_FORMAT "1")
set(dt_augmented_reality_swaggyduck_BUILD_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt_augmented_reality_swaggyduck_BUILD_EXPORT_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt_augmented_reality_swaggyduck_BUILDTOOL_DEPENDS "catkin")
set(dt_augmented_reality_swaggyduck_BUILDTOOL_EXPORT_DEPENDS )
set(dt_augmented_reality_swaggyduck_EXEC_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt_augmented_reality_swaggyduck_RUN_DEPENDS "duckietown_msgs" "roscpp" "rospy" "std_msgs")
set(dt_augmented_reality_swaggyduck_TEST_DEPENDS )
set(dt_augmented_reality_swaggyduck_DOC_DEPENDS )
set(dt_augmented_reality_swaggyduck_DEPRECATED "")