from .command_output import *
from .package_import import *
from .date import *
from .duckietown_repo import *
from .existence import *
from .groups import *
from .package_import import *
from .passwordless import *
from .permissions import *
from .file_contains import *
from .environment_variable import *
from .wifi import *
from .hostname import *
from .shells import *
from .github import *
from .internet_connected import *