set(_CATKIN_CURRENT_PACKAGE "duckietown_description")
set(duckietown_description_VERSION "1.0.0")
set(duckietown_description_MAINTAINER "Mack <mack@duckietown.org>")
set(duckietown_description_PACKAGE_FORMAT "1")
set(duckietown_description_BUILD_DEPENDS "roscpp" "rospy")
set(duckietown_description_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(duckietown_description_BUILDTOOL_DEPENDS "catkin")
set(duckietown_description_BUILDTOOL_EXPORT_DEPENDS )
set(duckietown_description_EXEC_DEPENDS "roscpp" "rospy")
set(duckietown_description_RUN_DEPENDS "roscpp" "rospy")
set(duckietown_description_TEST_DEPENDS )
set(duckietown_description_DOC_DEPENDS )
set(duckietown_description_DEPRECATED "")