
generate:
	@echo "$(sep)Automated files generation"
	@echo
	@echo "Generation of documentation"
	@echo
	@echo "  generate-easy_node        Generates the easy node documentation"
	@echo "  generate-easy_node-clean  Cleans the generated files"


generate-easy_node:
	rosrun easy_node generate_docs

generate-easy_node-clean:
	find . -name '*autogenerated.md' -delete
