#!/usr/bin/env python
import yaml

from duckietown_utils import col_logging  # @UnusedImport
from duckietown_utils.cli import d8app_run
from easy_logs.cli.generic import GenericLogDisplay


class Details(GenericLogDisplay):
    """ Shows detailed information for the logs. """ 
    def show_info(self, logs):
        for log in logs.values():        
            s = yaml.dump(log._asdict())
            print(s)
 

if __name__ == '__main__':
    d8app_run(Details)