#!/usr/bin/env python
import sys

from duckietown_utils import col_logging  # @UnusedImport
from duckietown_utils.exceptions import wrap_script_entry_point
from easy_logs.cli import dropbox_links_main


def dropbox_links():
    args = sys.argv[1:]
    if not args:
        query = '*'
    else:
        query = args[0]

    dropbox_links_main(query)
    

if __name__ == '__main__':
    wrap_script_entry_point(dropbox_links)
