#!/usr/bin/env python
# @create-shortcut-for-this
from duckietown_utils.cli import d8app_run
from easy_logs.cli.generic import GenericLogDisplay


class Find(GenericLogDisplay):
    """ Prints the filename for the specified log. """
    
    cmd = 'rosrun easy_logs find'
    
    def show_info(self, logs):
        for log in logs.values():
            print(log.filename)


if __name__ == '__main__':
    d8app_run(Find)
