#!/usr/bin/env python
import sys

from duckietown_utils import col_logging  # @UnusedImport
from duckietown_utils.exceptions import wrap_script_entry_point, DTUserError
from easy_logs.cli import require_main


def require():
    args = sys.argv[1:]
    if not args:
        msg = 'Expected at least one log name.'
        raise DTUserError(msg)
    
    require_main(args)
    

if __name__ == '__main__':
    wrap_script_entry_point(require)
