#!/usr/bin/env python
from duckietown_utils import col_logging  # @UnusedImport
from duckietown_utils.cli import d8app_run
from easy_logs.cli.easy_logs_summary_imp import format_logs
from easy_logs.cli.generic import GenericLogDisplay


class Summary(GenericLogDisplay):
    """ Shows a table summary for the logs. """
    def show_info(self, logs):
        s = format_logs(logs)
        print(s)


if __name__ == '__main__':
    d8app_run(Summary)
