#!/usr/bin/env python
from duckietown_utils.exceptions import wrap_script_entry_point
from duckietown_utils import col_logging  # @UnusedImport
from easy_logs.scripts.easy_logs_summary_imp import easy_logs_summary

def print_easy_logs_summary():
    s = easy_logs_summary()
    print(s)
        
    
if __name__ == '__main__':
    wrap_script_entry_point(print_easy_logs_summary)