#!/usr/bin/env python
# @create-shortcut-for-this
from duckietown_utils.cli import d8app_run

from easy_logs.cli.thumbnails import MakeThumbnails


if __name__ == '__main__':
    d8app_run(MakeThumbnails)
