"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mcomp_msgs.bool

class auto_pilot_msg(object):
    __slots__ = ["timestamp", "enabled"]

    def __init__(self):
        self.timestamp = 0.0
        self.enabled = mcomp_msgs.bool()

    def encode(self):
        buf = BytesIO()
        buf.write(auto_pilot_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.timestamp))
        assert self.enabled._get_packed_fingerprint() == mcomp_msgs.bool._get_packed_fingerprint()
        self.enabled._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auto_pilot_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auto_pilot_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auto_pilot_msg()
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        self.enabled = mcomp_msgs.bool._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auto_pilot_msg in parents: return 0
        newparents = parents + [auto_pilot_msg]
        tmphash = (0xe768e9a28b66c78d+ mcomp_msgs.bool._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auto_pilot_msg._packed_fingerprint is None:
            auto_pilot_msg._packed_fingerprint = struct.pack(">Q", auto_pilot_msg._get_hash_recursive([]))
        return auto_pilot_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

