"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class config(object):
    __slots__ = ["max_radius", "stop_radius", "latency"]

    def __init__(self):
        self.max_radius = 0.0
        self.stop_radius = 0.0
        self.latency = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(config._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.max_radius, self.stop_radius, self.latency))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != config._get_packed_fingerprint():
            raise ValueError("Decode error")
        return config._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = config()
        self.max_radius, self.stop_radius, self.latency = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if config in parents: return 0
        tmphash = (0x3712a2e739e3b15b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if config._packed_fingerprint is None:
            config._packed_fingerprint = struct.pack(">Q", config._get_hash_recursive([]))
        return config._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

