"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class event_msg(object):
    __slots__ = ["timestamp", "location", "vehicle", "vehicle_location", "description"]

    def __init__(self):
        self.timestamp = 0
        self.location = [ 0.0 for dim0 in range(2) ]
        self.vehicle = ""
        self.vehicle_location = [ 0.0 for dim0 in range(2) ]
        self.description = ""

    def encode(self):
        buf = BytesIO()
        buf.write(event_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>2d', *self.location[:2]))
        __vehicle_encoded = self.vehicle.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicle_encoded)+1))
        buf.write(__vehicle_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>2d', *self.vehicle_location[:2]))
        __description_encoded = self.description.encode('utf-8')
        buf.write(struct.pack('>I', len(__description_encoded)+1))
        buf.write(__description_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != event_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return event_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = event_msg()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.location = struct.unpack('>2d', buf.read(16))
        __vehicle_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicle = buf.read(__vehicle_len)[:-1].decode('utf-8', 'replace')
        self.vehicle_location = struct.unpack('>2d', buf.read(16))
        __description_len = struct.unpack('>I', buf.read(4))[0]
        self.description = buf.read(__description_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if event_msg in parents: return 0
        tmphash = (0x96d552b734d34b7b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if event_msg._packed_fingerprint is None:
            event_msg._packed_fingerprint = struct.pack(">Q", event_msg._get_hash_recursive([]))
        return event_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

