"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vgps_location_msg(object):
    __slots__ = ["timestamp", "location", "theta", "vehicle", "vehicle_id"]

    def __init__(self):
        self.timestamp = 0
        self.location = [ 0.0 for dim0 in range(2) ]
        self.theta = 0.0
        self.vehicle = ""
        self.vehicle_id = ""

    def encode(self):
        buf = BytesIO()
        buf.write(vgps_location_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>2d', *self.location[:2]))
        buf.write(struct.pack(">d", self.theta))
        __vehicle_encoded = self.vehicle.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicle_encoded)+1))
        buf.write(__vehicle_encoded)
        buf.write(b"\0")
        __vehicle_id_encoded = self.vehicle_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicle_id_encoded)+1))
        buf.write(__vehicle_id_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vgps_location_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vgps_location_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vgps_location_msg()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.location = struct.unpack('>2d', buf.read(16))
        self.theta = struct.unpack(">d", buf.read(8))[0]
        __vehicle_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicle = buf.read(__vehicle_len)[:-1].decode('utf-8', 'replace')
        __vehicle_id_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicle_id = buf.read(__vehicle_id_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vgps_location_msg in parents: return 0
        tmphash = (0x57a101a3f6ec0217) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vgps_location_msg._packed_fingerprint is None:
            vgps_location_msg._packed_fingerprint = struct.pack(">Q", vgps_location_msg._get_hash_recursive([]))
        return vgps_location_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

