# CMake generated Testfile for 
# Source directory: /home/yunfantang/duckietown/catkin_ws/src/20-indefinite-navigation/indefinite_navigation
# Build directory: /home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_indefinite_navigation_rostest_tests_calibrate_turn.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation/test_results/indefinite_navigation/rostest-tests_calibrate_turn.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/20-indefinite-navigation/indefinite_navigation --package=indefinite_navigation --results-filename tests_calibrate_turn.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation/test_results\" /home/yunfantang/duckietown/catkin_ws/src/20-indefinite-navigation/indefinite_navigation/tests/calibrate_turn.test ")
add_test(_ctest_indefinite_navigation_rostest_tests_calibrate_kinematics.test "/home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation/test_results/indefinite_navigation/rostest-tests_calibrate_kinematics.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/yunfantang/duckietown/catkin_ws/src/20-indefinite-navigation/indefinite_navigation --package=indefinite_navigation --results-filename tests_calibrate_kinematics.xml --results-base-dir \"/home/yunfantang/duckietown/catkin_ws/build_isolated/indefinite_navigation/test_results\" /home/yunfantang/duckietown/catkin_ws/src/20-indefinite-navigation/indefinite_navigation/tests/calibrate_kinematics.test ")
subdirs(gtest)
